import type { Category, MenuItem } from '@/types';

export const categories: Category[] = [
  { id: 'breakfast', name: 'Breakfast' },
  { id: 'lunch-dinner', name: 'Lunch & Dinner' },
  { id: 'desserts-pastries', name: 'Desserts & Pastries' },
];

export const menuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Swedish Meatballs',
    description: 'Classic meatballs served with mashed potatoes, cream sauce, and lingonberry jam.',
    price: 6.99,
    image: 'meatballs',
    category: 'lunch-dinner',
    isAvailable: true,
  },
  {
    id: '2',
    name: 'Salmon Fillet',
    description: 'Certified sustainable salmon with vegetable medallions and a lemon-dill sauce.',
    price: 8.99,
    image: 'salmon',
    category: 'lunch-dinner',
    isAvailable: true,
  },
  {
    id: '3',
    name: 'Plant Balls',
    description: 'A sustainable and delicious plant-based alternative, served like the original.',
    price: 5.99,
    image: 'plant-balls',
    category: 'lunch-dinner',
    isAvailable: true,
  },
  {
    id: '4',
    name: 'Veggie Hot Dog',
    description: 'A tasty veggie dog with red cabbage, pickled cucumber and fried onions.',
    price: 1.00,
    image: 'hot-dog',
    category: 'lunch-dinner',
    isAvailable: false,
  },
  {
    id: '5',
    name: 'Breakfast Plate',
    description: 'A hearty start with scrambled eggs, chicken sausage, and a potato hash brown.',
    price: 3.99,
    image: 'breakfast-plate',
    category: 'breakfast',
    isAvailable: true,
  },
  {
    id: '6',
    name: 'Swedish Pancakes',
    description: 'Three fluffy pancakes served with lingonberry jam or assorted fruits.',
    price: 4.49,
    image: 'pancakes',
    category: 'breakfast',
    isAvailable: true,
  },
  {
    id: '7',
    name: 'Cinnamon Bun',
    description: 'A beloved Swedish "fika" classic. Warm, soft, and perfectly spiced.',
    price: 1.49,
    image: 'cinnamon-bun',
    category: 'desserts-pastries',
    isAvailable: true,
  },
  {
    id: '8',
    name: 'Almondy Daim Cake',
    description: 'A crunchy almond base topped with golden cream and covered in milk chocolate.',
    price: 2.99,
    image: 'dime-cake',
    category: 'desserts-pastries',
    isAvailable: true,
  },
  {
    id: '9',
    name: 'Veggie Wrap',
    description: 'A healthy and refreshing wrap with vegetables and a light yogurt dressing.',
    price: 4.99,
    image: 'veggie-wrap',
    category: 'lunch-dinner',
    isAvailable: true,
  },
];
